recover_pjax/apps/apis/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

    # url(r'^register', views.index),
    url(r'search', views.search,name='search'),

]

recover_pjax/apps/content/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

    url(r'^show', views.show, name='show'),
    url(r'^bsi/$', views.bsi, name='bsi'),
    url(r'^music$', views.music, name='music'),
    url(r'^music2$', views.music2, name='music2'),
    url(r'^bsi/(?P<p_id>\d+)', views.bsi_cont, name='bsi_cont'),
    url(r'^ancient$', views.ancient, name='ancient'),
    url(r'^ancient/(?P<p_id>\d+)', views.ancient_cont, name='ancient_cont'),

    url(r'^news/(?P<tp>[a-z]+)/(?P<page>\d+)', views.news, name='news'),
    url(r'^contents/(?P<tpa>[a-z]+)/(?P<pn>\d+)', views.contents, name='contents'),

]

recover_pjax/apps/count/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

    # url(r'^register', views.index),
    url(r'^login/$', views.register, name='register'),
    url(r'^login1/$', views.login, name='login1'),
    url(r'^loginout/$', views.loginout, name='loginout'),
    url(r'^change/$', views.Change.as_view(), name='change'),
    url(r'^newpass/(\w+)/$', views.PasswordReset.as_view(), name="password_reset"),
    url(r'^users/$', views.ProfileView.as_view(), name='users'),

    url(r'^get_mobile_captcha/$', views.get_mobile_captcha, name='get_mobile_captcha'),
    url(r'^get_captcha/$', views.get_captcha, name='get_captcha'),
    url(r'^check_captcha/$', views.check_captcha, name='check_captcha'),

]

recover_pjax/apps/questions/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

    # url(r'^register', views.index),
    # url(r'details/all', views.details,name='detail'),
    url(r'details/a', views.adetails, name='detaila'),
    url(r'details/h', views.hdetails, name='detailh'),
    url(r'details/s', views.sdetails, name='details'),
    url(r'check/', views.check, name='check'),
    url(r'cancelc', views.cancelc, name='cancelc'),
    url(r'canceld', views.canceld, name='canceld'),
    url(r'sc/(?P<id>\d+)', views.QuestionCollectionView.as_view(), name='sc'),
    url(r'dz/(?P<id>\d+)', views.QuestionlikeView.as_view(), name='dz'),

]

recover_pjax/recover/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# from django.contrib.staticfiles.urls import
# from apps.count import views
from apps.content import views
from recover import settings
from django.contrib.staticfiles.views import static

# import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index),
    url(r'^index', views.index, name='index'),
    url(r'^music', views.music, name='music'),



    url(r'^count/', include('apps.count.urls', namespace='count')),
    url(r'^content/', include('apps.content.urls', namespace='countent')),
    url(r'^questions/', include('apps.questions.urls', namespace='questions')),
    url(r'^apis/', include('apps.apis.urls', namespace='apis')),

    # 404定制
    url(r'^static/(?P<path>.*)$', static.serve,{'document_root': settings.STATIC_ROOT}, name='static')
]

handler404=views.my404
#

recover_pjax/apps/content/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser
# Create your models here.
#
# class User(AbstractUser):
#
#     # 答题系统待开发
class Video(models.Model):
    # 继承自AbstractUser
    titles = models.CharField(max_length=100, verbose_name="视频标题")
    imgurl = models.CharField(max_length=100, verbose_name='图片地址')
    videoid = models.CharField(max_length=101, verbose_name="视频id")

recover_pjax/apps/questions/models.py
from django.db import models
from apps.count.models import User


# Create your models here.


class Category(models.Model):
    """分类"""
    name = models.CharField("分类名称", max_length=64)

    class Meta:
        verbose_name = "分类"
        verbose_name_plural = verbose_name

    def __str__(self):
        return f"{self.name}"


class Questions(models.Model):
    """题库"""
    category = models.ForeignKey(Category, verbose_name="所属分类", null=True)
    title = models.CharField(verbose_name="题目", unique=True, max_length=255)
    content = models.CharField(verbose_name="题目解析", null=True, max_length=100)
    answer = models.CharField(verbose_name="题目答案", null=True, max_length=100)
    choose_A = models.CharField(verbose_name='A选项', max_length=100)
    choose_B = models.CharField(verbose_name='B选项', max_length=100)
    choose_C = models.CharField(verbose_name='C选项', max_length=100)
    choose_D = models.CharField(verbose_name='D选项', max_length=100)
    choose_E = models.CharField(verbose_name='E选项', max_length=100)


    class Meta:
        verbose_name = "题库"
        verbose_name_plural = verbose_name
        permissions = (
            ('can_change_question', "可以修改题目信息"),
            ('can_add_question', "可以添加题目信息"),
        )

    def __str__(self):
        return f"{self.id}:{self.title}"


class QuestionsCollection(models.Model):
    """收藏问题"""
    question = models.ForeignKey(Questions, verbose_name="问题")
    user = models.ForeignKey(User, verbose_name="收藏者" )
    create_time = models.DateTimeField("收藏/取消时间", auto_now=True)
    # True表示收藏 ,False表示未收藏
    status = models.BooleanField("收藏状态", default=True)

    class Meta:
        verbose_name = "收藏记录"
        verbose_name_plural = verbose_name



class Questionsliker(models.Model):
    """喜欢问题"""
    question = models.ForeignKey(Questions, verbose_name="问题" )
    user = models.ForeignKey(User, verbose_name="喜欢者")
    create_time = models.DateTimeField("喜欢/取消时间", auto_now=True)
    # True表示收藏 ,False表示未收藏
    status = models.BooleanField("喜欢状态", default=True)

    class Meta:
        verbose_name = "喜欢记录"
        verbose_name_plural = verbose_name

recover_pjax/apps/content/views.py
from django.shortcuts import render,HttpResponse
from django.template.response import TemplateResponse
from django.contrib.auth.decorators import login_required
from apps.count.models import News
from .models import Video
import page_splie
import json
import re
import time
from libs import search
from django.views.generic import View, DetailView



# 新闻首页
def index(request):
    if request.session.get('user'):
        h_objec = News.objects.filter(category_id=1).order_by('-news_id')[0]
        s_objec = News.objects.filter(category_id=2).order_by('-news_id')[0]
        q_objec = News.objects.filter(category_id=3).order_by('-news_id')[0]
        user = request.session.get('user', 'me')
        return render(request, 'index.html', {'h': h_objec, "s": s_objec, 'q': q_objec, 'user': user})
    else:
        h_objec = News.objects.filter(category_id=1).order_by('-news_id')[0]
        s_objec = News.objects.filter(category_id=2).order_by('-news_id')[0]
        q_objec = News.objects.filter(category_id=3).order_by('-news_id')[0]
        return TemplateResponse(request, 'index.html', {'h': h_objec, "s": s_objec, 'q': q_objec, })


def my404(requset):
    return render(requset, '404.html')

# 获取音乐
def music(request):
    try:
        nname = request.POST.get("name")
        n =request.POST.get('num')
        ress = search.start(nname,str(n))

        for i in range(len(ress)):
            ress[i]['cover'] = 'http://p4.music.126.net/YXY1vPG5rtdV7w_cWDnNWw==/884007348732141.jpg?param=106x106'
        return HttpResponse(json.dumps(ress))
    except:
        ress={'artist_id':123}
        print(ress)
        return HttpResponse(json.dumps(ress))
#     换一批
def music2(request):
    try:
        n = request.POST.get("num")
        nname = request.POST.get("name")
        ress = search.start(nname,str(n))
        for i in range(len(ress)):
            ress[i]['cover'] = 'http://p4.music.126.net/YXY1vPG5rtdV7w_cWDnNWw==/884007348732141.jpg?param=106x106'
        return HttpResponse(json.dumps(ress))
    except:
        ress={'artist_id':123}
        return HttpResponse(json.dumps(ress))



# 新闻
def news(request, tp, page):
    if request.method == "GET":
        banner = News.objects.filter(category_id__in=[1, 2, 3]).order_by('-time')[0:11]

        if tp == 'h':
            cout = News.objects.filter(category_id=1).count()
            # c_obj = News.objects.filter(category_id=1).order_by('-news_id')[0:8]
            page_info = page_splie.Pageinfo(int(page), cout, 6, '/content/news/', tp, showpage=7)
            z_c_obj = News.objects.filter(category_id=1).order_by('-news_id')[page_info.start():page_info.end()]
            return TemplateResponse(request, 'news.html', {'z_c_obj': z_c_obj, "pageinfo": page_info,"banner":banner})
        elif tp == 's':
            cout = News.objects.filter(category_id=2).count()
            # c_obj = News.objects.filter(category_id=1).order_by('-news_id')[0:8]
            page_info = page_splie.Pageinfo(int(page), cout, 6, '/content/news/', tp, showpage=7)
            z_c_obj = News.objects.filter(category_id=2).order_by('-news_id')[page_info.start():page_info.end()]
            return TemplateResponse(request, 'news.html', {'z_c_obj': z_c_obj, "pageinfo": page_info,"banner":banner})
        elif tp == 'q':
            cout = News.objects.filter(category_id=3).count()
            # c_obj = News.objects.filter(category_id=1).order_by('-news_id')[0:8]
            page_info = page_splie.Pageinfo(int(page), cout, 6, '/content/news/', tp, showpage=7)
            z_c_obj = News.objects.filter(category_id=3).order_by('-news_id')[page_info.start():page_info.end()]
            return TemplateResponse(request, 'news.html', {'z_c_obj': z_c_obj, "pageinfo": page_info,"banner":banner})
        elif tp == 'a':
            cout = News.objects.all().count()
            # c_obj = News.objects.filter(category_id=1).order_by('-news_id')[0:8]
            page_info = page_splie.Pageinfo(int(page), cout, 6, '/content/news/', tp, showpage=7)
            z_c_obj = News.objects.filter(category_id__lte=3).order_by('-time')[page_info.start():page_info.end()]
            return TemplateResponse(request, 'news.html', {'z_c_obj': z_c_obj, "pageinfo": page_info,"banner":banner})
        else:
            return TemplateResponse(request, 'news.html')

# 内容
def contents(request, tpa, pn):
    if request.method == "GET":
        if tpa == "h":
            content = News.objects.get(news_id=int(pn))
            return render(request, 'contents.html', {'cont': content})
        elif tpa == "s":
            content = News.objects.get(news_id=int(pn))
            return render(request, 'contents.html', {'cont': content})
        elif tpa == "q":
            content = News.objects.get(news_id=int(pn))
            return render(request, 'contents.html', {'cont': content})
        else:
            return render(request, 'news.html')

# 古人
def ancient(request):
    if request.method == 'GET':

        cc = News.objects.filter(category_id=4)
        return TemplateResponse(request, 'ancient.html', {'cat': cc})
    else:
        return TemplateResponse(request, 'ancient.html')


def ancient_cont(request, p_id):
    if request.method == "GET":
        p_id = int(p_id)
        content = News.objects.get(news_id=p_id)
        return TemplateResponse(request, 'a_contact.html', {'content': content})

# 小技巧
def bsi(request):
    if request.method == 'GET':

        cc = News.objects.filter(category_id=5)
        return TemplateResponse(request, 'bsi.html', {'cat': cc})
    else:
        return TemplateResponse(request, 'bsi.html')


def bsi_cont(request, p_id):
    if request.method == "GET":
        p_id = int(p_id)
        content = News.objects.get(news_id=p_id)
        return TemplateResponse(request, 'bsi_contents.html', {'content': content})

recover_pjax/templates/bsi.html
{% extends 'base.html' %}
{% block count %}
    <div id="aim-pjax">
        <div class="info-container">
            <div class="info-container-title">
                <h2>环保小妙招~</h2>
            </div>
            <div class="info-container-list clearfix">
                {% for i in cat %}
                    <div class="info-listItem">
                        <dl class="info-listItem-list">
                            <dt>
                                <a href="#">
                                    <img src="{{ i.img_url }}" alt="">
                                    <span>{{ i.s_title }}</span>
                                </a>
                            </dt>
                        </dl>
                        <a href="/content/bsi/{{ i.news_id }}" data-pjax="true" class="info-more">查看更多</a>
                    </div>
                {% endfor %}

            </div>
        </div>
    </div>
{% endblock %}

recover_pjax/templates/bsi_contents.html
{% extends 'base.html' %}


{% block count %}
     <div id="aim-pjax">
    <div class="row wrapper">

        <div class="col-md-12 wrapper ">

            <div class="cistLift" style="width: 1000px">

                <div class="leftTop">
                    {{ content.title|safe }}
                    <div class="qefwer">文章来源：搜狐网</div>
                </div>
                <div class="newsContent">
                    {{ content.content|safe }}
                </div>
                <div class="refer">文章来源：搜狐网</div>

            </div>

        </div>
{#        <div class="col-md-3"><p>asdsadsadsad</p></div>#}

    </div>

    <script>
        $("p:has(img)").addClass('forp')
    </script>
       <script>
                $(document).pjax('a[data-pjax]', '#showser', {fragment: '#aim-pjax', timeout: 8000});


                // pjax链接点击后显示加载动画；
                $(document).on('pjax:send', function () {
                    NProgress.start();
                });
                // pjax链接加载完成后隐藏加载动画；
                $(document).on('pjax:complete', function () {
                    NProgress.done();
                });
            </script>
     </div>

{% endblock %}

recover_pjax/templates/chagepass.html
{% extends 'base.html' %}
{% block count %}
    <script src="/static/js/jquery.js"></script>
    <!-- header area end -->
    <!-- breadcroumb area start -->
    <div class="mayabi-breadcroumb blue-bg text-center sec-p-100">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2>login</h2>
                    <h4><a href="/index/" data-pjax="true">主页 </a>/ 登录</h4>
                </div>
            </div>
        </div>
    </div>

    {#   注册登录 表单#}
    <div class="register-login-area sec-p-100">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="mayabi-register-area">
                                <div class="cart-title mb-20">
                                    <h2>找回密码</h2>
                                </div>
                                {#                               注册#}
                                <form method="post" class="registration-form" id="sendemail" novalidate>
                                    {% csrf_token %}
                                    <div class="single-field mb-30">
                                        <input class="form-control" type="text" name="email"
                                               placeholder="请输入邮箱*">
                                        <span><i class="fa fa-user" style="width: 150px;height:27px;"></i></span>
                                    </div>

                                    <button class="btn btn-type-3" id="register_btn" style="margin-left: 45%" type="button" onclick="send()">
                                        发送
                                    </button>
                                </form>
                            </div>

                        </div>
                    </div>
                </div>

            </div>

        </div>
    </div>
    <!-- cart area end -->
    <!-- footer area start -->
        <script>
    function send() {
        $.ajax({
            url:'{% url "count:change" %}',
            type:'post',
            data:$('#sendemail').serialize(),
            success:function (msg) {
                console.log(msg);
                if(msg.code==200){
                    alert(msg.msg)
                }else {
                    alert(msg.msg)
                }
            },
            error:function () {
                alert('失败')
            }
        })
    }
    </script>

{% endblock %}

recover_pjax/templates/contents.html
{% extends 'base.html' %}
{% block count %}
    <div id="aim-pjax">
        <div class="row wrapper">

            <div class="col-md-12 wrapper " style="width: 1000px">

                <div class="cistLift">

                    <div class="leftTop">
                        {{ cont.title|safe }}
                        <div class="qefwer">新闻来源：环保在线新闻网</div>

                    </div>

                    <div class="abstract">
                        {{ cont.abstrat|safe }}
                    </div>
                    <div class="newsContent">
                        {{ cont.content|safe }}
                    </div>
                    <div class="refer">新闻来源：环保在线新闻网</div>

                </div>

            </div>
        </div>
    </div>
{% endblock %}

recover_pjax/templates/newpass.html
{% extends 'base.html' %}
{% block count %}
    <script src="/static/js/jquery.js"></script>
    <!-- header area end -->
    <!-- breadcroumb area start -->
    <div class="mayabi-breadcroumb blue-bg text-center sec-p-100">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2>login</h2>
                    <h4><a href="/index/">主页 </a>/ 登录</h4>
                </div>
            </div>
        </div>
    </div>

    {#   注册登录 表单#}
    <div class="register-login-area sec-p-100">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="mayabi-register-area">
                                <div class="cart-title mb-20">
                                    <h2>新密码</h2>
                                </div>
                                {#                               注册#}
                                <form method="post" class="registration-form" id="repass" novalidate>
                                    {% csrf_token %}
                                    <div class="single-field mb-30">
                                        <input class="form-control" type="text" name="password1"
                                               placeholder="请输入新密码*">
                                        <span><i class="fa fa-unlock-alt" style="width: 150px;height:27px;"></i></span>
                                    </div>
                                    <div class="single-field mb-30">
                                        <input class="form-control" type="text" name="password2"
                                               placeholder="确认新密码*">
                                        <span><i class="fa fa-unlock-alt" style="width: 150px;height:27px;"></i></span>
                                    </div>
                                    <button type="button" class="btn btn-type-3" style="margin-left: 45%" onclick="cpass()">提交</button>
{#                                    <input type="submit" name="" id="" value="提交">#}
                                </form>
                            </div>

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- cart area end -->
    <!-- footer area start -->

{% endblock %}

{% block js %}
    <script>
        function cpass() {
            $.ajax({
                url: "{{ urls }}",
                type: 'post',
                data: $('#repass').serialize(),
                success: function (msg) {
                    if (msg.code==401){
                        msg=msg.msg
                    }else if(msg.code==402){
                        msg=msg.msg
                    }else if(msg.code==200){
                          window.location.href = '{% url 'count:register' %}';

                    } else if (msg.code==404) {
                        msg=msg.msg
                    }
                    $.gritter.add({
                        // (string | mandatory) the heading of the notification
                        title: '提交结果',
                        // (string | mandatory) the text inside the notification
                        //text: 'This will fade out after a certain amount of time. Vivamus eget tincidunt velit. Cum sociis natoque penatibus et <a href="#" style="color:#ccc">magnis dis parturient</a> montes, nascetur ridiculus mus.'
                        text: msg
                    });
                }
            })
        }
    </script>

{% endblock %}

recover_pjax/templates/news.html
{% extends 'base.html' %}
{% block css %}
    <style>

        .cistLift {
            width: 800px;
            padding-left: 20px;
            float: left;
        }

        .leftBox {
            width: 800px;
            float: left;
            margin-bottom: 20px;
            padding-bottom: 20px;
            border-bottom: 1px dashed #ddd;
        }

        .leftBox h3 {
            width: 590px;
            float: right;
        {#height: 25px;#} overflow: hidden;
        }

        .leftBox h3 a {
            font-size: 18px;
            line-height: 25px;
            color: #333;
            font-weight: 900;
        }

        .leftBox h3 img {
            margin-left: 10px;
            position: relative;
            top: -3px;
        }

        .leftBox > a > img {
            width: 188px;
            height: 110px;
            margin-right: 20px;
            float: left;
        }

        .leftBox p {
            width: 590px;
            float: right;
            font-size: 16px;
            line-height: 25px;
            color: #666;
            margin-top: 5px;
            height: 50px;
            overflow: hidden;
        }

        a {
            text-decoration: none;
            color: #333;
        }

        .leftBox .read {
            width: 590px;
            float: right;
            margin-top: 10px;
            position: relative;
            text-align: right;
        }

        .leftBox .read > span {
            font-size: 12px;
            line-height: 20px;
            color: #999;
            /* font-family: "\5b8b\4f53"; */
            padding-left: 25px;
            display: inline-block;
            margin-left: 17px;
        }

        .wrapper {
            width: 1180px;
            margin: auto;
            margin-top: 50px;
            background: #fff;
            /* padding-bottom: 30px; */
        }
    </style>
{% endblock %}
{% block count %}
    <div id="aim-pjax">

        <div class="row wrapper">
            <div class="col-md-9 wrapper ">
                <div class="cistLift">
                    {% for i in  z_c_obj %}
                        <div class="leftBox">
                            {{ i.s_title|safe }}
                            {{ i.img_url|safe }}
                            {{ i.s_ab|safe }}
                            <div class="read">
                                <span>{{ i.time }}</span>
                            </div>
                            {#                        <p class="cl-card-more"><a href="/content/?pid={{ i.id }}">阅读更多...</a></p>#}
                        </div>
                    {% endfor %}
                </div>
            </div>
            {% for i in s %}
                <a href="{{ i.0 }}" data-pjax="true">{{ i.0 }}</a>
            {% endfor %}
            <div class="col-md-3">
                <div style="margin-top: 65px;margin-bottom: 65px"><img style="width: 280px"
                                                                       src="/static/img/index/search.jpg" alt=""></div>
                <h3 style="font-size: 22px;font-weight: 500;margin-bottom: 19px;">时时刻刻做好垃圾分类</h3>
                <div class="single-sid-wdg" style="background: #f8f8f8;">
                    <h4 class="sid-wdg-title"><strong>搜搜看</strong> 嗖~
                        <span></span></h4>
                    <form action="#" class="wdg-search-form">
                        <input type="text" placeholder="垃圾分类我知道~..." id="contents">
                        <button class="submit-btn" type="button" onclick="find()"><i class="fa fa-search"></i></button>
                    </form>
                    <div id="show_answer"></div>
                    <div id="show_answer2"></div>
                </div>
            </div>

            <script>
                function find() {
                    $.ajax({
                        url: '{%  url "apis:search" %}',
                        type: 'get',
                        data: {'kw': $('#contents').val()},
                        success: function (msg) {
                            $('#show_answer').removeClass('hide');
                            $('#show_answer2').children().remove();
                            var lan = msg.ak;
                            if (lan == 1) {
                                $('#show_answer').html('好像找不到哦，换一个姿势试一试~');

                            } else {
                                $('#show_answer').html('为您搜到以下结果：');
                                $('#show_answer').attr('style', 'margin-bottom: 10px;');
                                var page = $('<p>');
                                var span = $('<span>');
                                var br = $('<Br/>');
                                page.html(Object.keys(msg.detail)[0]);
                                page.attr('class', 'fu');
                                page.attr('style', 'font-size:17px;');
                                span.html(":" + Object.values(msg.detail)[0]);
                                span.attr('class', 'fu');
                                $('#show_answer2').append(page);
                                $('#show_answer2').append(span);
                                $('#show_answer2').append(br);
                                if (Object.values(msg.detail)[0] == "干垃圾") {
                                    var img = $('<img>');
                                    var pages = $('<p>');
                                    pages.html('干垃圾，是人制造的产生的垃圾，比如纸，塑料袋，啤酒瓶。这其中如果有有害垃圾再放在有害垃圾 ')
                                    img.attr('src', '/static/img/index/glt.png', 'style', 'width:250px;margin-left:-26px');
                                    img.attr('style', 'width:250px;margin-left:-26px');
                                    pages.attr('style', 'margin-top: 20px;');
                                    $('#show_answer2').append(pages);
                                    $('#show_answer2').append(img);

                                }
                                else if(Object.values(msg.detail)[0] == "湿垃圾"){
                                    var img = $('<img>');
                                    var pages = $('<p>');
                                    pages.html('湿垃圾又称为厨余垃圾、有机垃圾，即易腐垃圾，指食材废料、剩菜剩饭、过期食品、瓜皮果核、花卉绿植、中药药渣等易腐的生物质生活废弃物。')
                                    img.attr('src', '/static/img/index/st.png', 'style', 'width:250px;margin-left:-26px');
                                    img.attr('style', 'width:250px;margin-left:-26px');
                                    pages.attr('style', 'margin-top: 20px;');
                                    $('#show_answer2').append(pages);
                                    $('#show_answer2').append(img);
                                }else if(Object.values(msg.detail)[0] == "可回收"){
                                    var img = $('<img>');
                                    var pages = $('<p>');
                                    pages.html('可回收物就是可以再生循环的垃圾。本身或材质可再利用的纸类、硬纸板、玻璃、塑料、金属、塑料包装，与这些材质有关的如：报纸、杂志、广告单及其它干净的纸类等皆可回收。')
                                    img.attr('src', '/static/img/index/hst.png', 'style', 'width:250px;margin-left:-26px');
                                    img.attr('style', 'width:250px;margin-left:-26px');
                                    pages.attr('style', 'margin-top: 20px;');
                                    $('#show_answer2').append(pages);
                                    $('#show_answer2').append(img);
                                }else if(Object.values(msg.detail)[0] == "有害垃圾"){
                                    var img = $('<img>');
                                    var pages = $('<p>');
                                    pages.html('有害垃圾指废电池、废灯管、废药品、废油漆及其容器等对人体健康或者自然环境造成直接或者潜在危害的生活废弃物。')
                                    img.attr('src', '/static/img/index/yht.png', 'style', 'width:250px;margin-left:-26px');
                                    img.attr('style', 'width:250px;margin-left:-26px');
                                    pages.attr('style', 'margin-top: 20px;');
                                    $('#show_answer2').append(pages);
                                    $('#show_answer2').append(img);
                                }
                            }
                        }
                    })
                }
            </script>
        </div>
        {# 分页#}
        <nav aria-label="Page navigation example" style="margin-top: 30px">
            <ul class="pagination justify-content-center">
                {{ pageinfo.a_page |safe }}
            </ul>
        </nav>
    </div>
{% endblock %}